version: 1.0.{build}
environment:
  main_project: oscript-component
before_build:
- ps: nuget restore
init:
- ps: Set-WinSystemLocale ru-RU
- ps: Start-Sleep -s 5
- ps: Restart-Computer
install:
- cmd: >-
    mkdir engine

    cd engine

    appveyor DownloadFile http://oscript.io/downloads/latest/exe -FileName os.exe

    os.exe /silent

    set PATH=%ProgramFiles(x86)%\OneScript\bin;%PATH%

    cd ..
    
    appveyor DownloadFile https://github.com/EvilBeaver/OneScriptDocumenter/releases/download/0501_18/documenter.zip -FileName OneScriptDocumenter.zip
    
    7z x OneScriptDocumenter.zip > NUL

    oscript -version

    opm install opm

    choco install rabbitmq --ignoredependencies -y

    appveyor DownloadFile http://127.0.0.1:15672/cli/rabbitmqadmin -FileName rabbitmqadmin.py

    python rabbitmqadmin.py declare exchange name=test type=direct

    python rabbitmqadmin.py declare queue name=test durable=true

    python rabbitmqadmin.py declare binding source="test" destination_type="queue" destination="test"

build:
  verbosity: minimal
configuration: Release
test_script:
- cmd: nunit3-console --x86 NUnitTests\bin\%CONFIGURATION%\NUnitTests.dll

after_build:
- cmd: >-

    del %main_project%\bin\%CONFIGURATION%\*.pdb

    mkdir bin

    OneScriptDocumenter.exe json bin\syntaxHelp.json %main_project%\bin\%CONFIGURATION%\%main_project%.dll
    
    del %main_project%\bin\%CONFIGURATION%\ScriptEngine. %main_project%\bin\%CONFIGURATION%\NewtonSoft. %main_project%\bin\%CONFIGURATION%\DotNetZip.
    
    xcopy %main_project%\bin\%CONFIGURATION%\* bin\

    opm build .
    
artifacts:
- path: .\*.ospx
  name: component
